[phases.setup]
nixPkgs = ["python39", "gcc"]

[phases.install]
cmds = [
  "python -m ensurepip",
  "python -m pip install --upgrade pip",
  "python -m pip install -r requirements.txt"
]
[start]
cmd = "gunicorn inventory.wsgi"
